Fix corehq.motech.repeaters.tests.test_repeater:RepeaterTest.test_automatic_cancel_repeat_record
AttributeError: 'SQLRepeatRecord' object has no attribute 'handle_failure'
Also fix ServerErrorTests, which were broken due to state bleeding across test boundaries.